version : 2.1

jobs:
  welcome:
     machine : true
     parameters:
         name_to_print:
            type: string
            default: “hello world”
     steps:
         -run: 
             name : "print hello"
             command : echo <<parameters.name_to_print>>

workflows:
   workflow1:
      version: 2
      jobs:
        -welcome:
           name_to_print : “hello metacube”
