version : 2.1

jobs:
  welcome:
    machine : true
    parameters:
        nameToPrint:
            type: string
            default: “hello world”
    steps:
        - run: 
            name : print hello
            command : echo <<parameters.nameToPrint>>

workflows:
    version: 2
    helloFlow:
      jobs:
        - welcome:
           nameToPrint : “hello metacube”
