server:
  port: 8080
spring:
  mvc:
   view:
    prefix: /WEB-INF/view/
    suffix: .jsp
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: root
   
home:
 message : Welcome Student!
